In [10]:
import pandas as pd
import numpy as np

print("Dataset Exploration Started 🚀")

Dataset Exploration Started 🚀

In [18]:
resume_df = pd.read_csv("../data/raw/resumes/Resume.csv")
jobs_df = pd.read_csv("../data/raw/job_descriptions/job_title_des.csv")

In [19]:
print("Resume Dataset Shape:", resume_df.shape)
print("Job Dataset Shape:", jobs_df.shape)

Resume Dataset Shape: (9544, 35)
Job Dataset Shape: (2277, 3)

In [20]:
resume_df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database warehouse manager with robust experience in handling all kinds of data. I have also used multiple cloud infrastructure services and am well acquainted with them. Currently in search of role that offers more of development.,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapreduce', 'Spark', 'Java', 'Machine Learning', 'Cloud', 'Hdfs', 'YARN', 'Core Java', 'Data Science', 'C++', 'Data Structures', 'DBMS', 'RDBMS', 'Informatica', 'Talend', 'Amazon Redshift', 'Microsoft Azure']","['The Amity School of Engineering & Technology (ASET), Noida']",['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a reputed university.,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaboration\nDocumentation\nSystem Monitoring\nSoftware Deployment\nTraining & Mentorship\nIndustry Trends\nField Visits\n\n\n\n\n,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and junior data scientist. Experienced in creating meaningful data dashboards and evaluation models.,"['Data Analysis', 'Data Analytics', 'Business Analysis', 'R', 'SAS', 'PowerBi', 'Tableau', 'Data Visualization', 'Business Analytics', 'Machine Learning']","['Delhi University - Hansraj College', 'Delhi University - Hansraj College']","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in any relevant discipline from a reputed University,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional Collaboration\nStrategy Development\nML/NLP Infrastructure\nPrototype Transformation\nML System Design\nAlgorithm Research\nApplication Development\nDataset Selection\nML Testing\nStatistical Analysis\nR&D in ML/NLP\nText Representation\nData Pipeline Design\nStatistical Data Analysis\nModel Training\nTeam Collaboration\nResearch Reporting\nAlgorithm Analysis,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', 'Deep Learning', 'Risk Assessment', 'Requirement Gathering', 'Application Support', 'JavaScript', 'Python', 'Docker', 'HTML', 'Hive', 'CSS', 'C', 'C++']","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, Hygiene Products",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, Sales Targets\nField Marketing, Campaigns, Product Distribution\nBrand Head\nExcel, KPIs Tracking",Brand Promotion\nCampaign Management\nField Supervision\nMerchandising\npromotional activities\nTrade Marketing,0.416667
3,NaN,"To obtain a position in a fast-paced business office environment, demanding a strong organizational, technical, and interpersonal position utilizing my skills and attributes.","['accounts payables', 'accounts receivables', 'Accounts Payable', 'Accounts Receivable', 'administrative functions', 'trial balance', 'banking', 'budget', 'bi', 'closing', 'Computer Applications', 'Credit', 'clients', 'Customer Service', 'data entry', 'delivery', 'driving', 'email', 'insurance', 'inventory', 'ledger', 'Access', 'Excel', 'Outlook', 'PowerPoint', 'Word', 'mortgage loan', 'Enterprise', 'policies', 'QuickBooks', 'Sales', 'sales reports', 'telecommunications', 'phone', 'workflow', 'written']","['Martinez Adult Education, Business Training Center ï¼ City , State']",['Computer Applications Specialist Certificate Program'],['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name ï¼ City , State', 'Company Name ï¼ City , State', 'Company Name ï¼ City , State', 'Company Name ï¼ City , State', 'N/A']",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nReliable Partner\nBuyer/Vendor Communication,Fast typing skill\nIELTSInternet browsing & online work ability.,0.760000
4,NaN,"Professional accountant with an outstanding work ethic and integrity seeking to make a valuable contribution utilizing strong analytical, organizational, communication, and computer skills.","['Analytical reasoning', 'Compliance testing knowledge', 'Effective time management', 'Public and private accounting', 'accounting', 'accounting systems', 'accounts payable', 'accounts receivable', 'administrative', 'AR', 'billing', 'closing', 'client', 'clients', 'documentation', 'financial', 'financial reports', 'preparation of financial reports', 'Preparation of financial statements', 'fixed assets', 'managing', 'month-end closing', 'policies', 'maintain records', 'reporting', 'Research', 'sales', 'tax', 'taxes', 'tax returns', 'annual reports', 'year-end']",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name', 'Company Name', 'Company Name']",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Frameworks\niOS Development\nAPI Integration\nTechnical Communication\nUI Design\nPerformance Optimization\nFeature Collaboration\nBug Fixing\nCode Translation\nHigh-Performance Development\nTask Management\nCross-Team Collaboration\nCode Quality,iOS\niOS App Developer\niOS Application Development\niOS Development\nMobile apps Developer (iOS)\nNative IOS\nSwift (iOS)\nSwift UI,0.650000

In [21]:
jobs_df.head()

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,"We are looking for hire experts flutter developer. So you are eligible this post then apply your resume.\nJob Types: Full-time, Part-time\nSalary: ₹20,000.00 - ₹40,000.00 per month\nBenefits:\nFlexible schedule\nFood allowance\nSchedule:\nDay shift\nSupplemental Pay:\nJoining bonus\nOvertime pay\nExperience:\ntotal work: 1 year (Preferred)\nHousing rent subsidy:\nYes\nIndustry:\nSoftware Development\nWork Remotely:\nTemporarily due to COVID-19"
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ - 04)\nStrong Python experience in API development (REST/RPC).\nExperience working with API Frameworks (Django/flask).\nExperience evaluating and improving the efficiency of programs in a Linux environment.\nAbility to effectively handle multiple tasks with a high level of accuracy and attention to detail.\nGood verbal and written communication skills.\nWorking knowledge of SQL.\nJSON experience preferred.\nGood knowledge in automated unit testing using PyUnit.
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n\nResponsibilities\n\nWe are looking for a capable data scientist to join the Analytics team, reporting locally in India Bangalore. This person’s responsibilities include research, design and development of Machine Learning and Deep Learning algorithms to tackle a variety of Fraud oriented challenges. The data scientist will work closely with software engineers and program managers to deliver end-to-end products, including: data collection in big scale and analysis, exploring different algorithmic approaches, model development, assessment and validation – all the way through production.\n\nQualifications\n\nAt least 3 years of hands-on development of complex Machine Learning models using modern frameworks and tools, ideally Python based.\nSolid understanding of statistics and applied mathematics\nCreative thinker with a proven ability to tackle open problems and apply non-trivial solutions.\nExperience in software development using Python, Java or a similar language.\nAny Graduate or M.Sc. in Computer Science, Mathematics or equivalent, preferably in Machine Learning\nAbility to write clean and concise code\nQuick learner, independent, methodical, and detail oriented.\nTeam player, positive attitude, collaborative, good communication skills.\nDedicated, makes things happen.\nFlexible, capable of making decisions in an ambiguous and changing environment.\n\nAdvantages:\n\nPrior experience as a software developer or data engineer – advantage\nExperience with Big data – advantage\nExperience with Spark – big advantage\nExperience with Deep Learning frameworks (PyTorch, TensorFlow, Keras) – advantage.\nExperience in the Telecommunication domain and/or Fraud prevention - advantage"
3,3,iOS Developer,"JOB DESCRIPTION:\n\nStrong framework outside of iOS is always a plus\n\niOS experience and generalist engineers with backgrounds in related technologies is a plus\n\nA disciplined approach to development, documentation and file structure\n\nStrong visual design sense and excellent taste\n\nA constant desire to improve, learn more and take things higher\n\nAn excellent understanding of networking, mobile network issues, concurrency and threading\n\nExperience working with internationalized apps\n\nRESPONSIBILITIES\nDesign and build advanced applications for the iOS platform.\nCollaborate with cross-functional teams to define, design, and ship new features..\nWork on bug fixing and improving application performance.\nContinuously discover, evaluate, and implement new technologies to maximize development efficiency.\nHave published one or more iOS apps in the app store.\nA deep familiarity with Objective-C and Cocoa Touch.\nExperience working with iOS frameworks such as Core Data, Core Animation, Core Graphics and Core Text.\nExperience with third-party libraries and APIs.\nWorking knowledge of the general mobile landscape, architectures, trends, and emerging technologies.\nSolid understanding of the full mobile development life cycle.\nResponsible for working on different layers of the iOS apps.\nHelp architect and maintain our set of native mobile applications."
4,4,Full Stack Developer,job responsibility full stack engineer – react role make impact petsmart transforming engineering team meet need rapidly changing retail environment role foundational helping build craft petsmart ’ prowess making react j native key framework across mobile web property working across web mobile application part building amazing mobile first customer experience impact customer store digital channel goal responsibility include act full stack developer across petsmart ’ various web mobile solution full stack engineer help build petsmart ’ competency using react j native across mobile web property partner web engineering team strategy share component across application best practice new advancement react community work product ux team review design concept offer suggestion decrease complexity maintaining spirit experience proactively make recommendation technical enhancement better performance scalability maintainability accountable delivering agile environment creates/oversees completion technical development mobile web solution work cross functional business team design develop solution based business requirement identify area improvement design implementation process tooling automated testing quality assurance mentor le experienced developer remain current latest web technology seeking integrate solution appropriate ’ bring table 5+ year hands-on experience web development 2+ year recent experience working react strong experience various j library framework redux angular vue etc expert understanding javascript html cs restful apis http networking concept full stack web development architecture expertise experience mvc object-oriented programming concept experience implementing responsive design adaptive design demonstrated strong front-end development skill especially concerning accessibility extensibility client-side computing object-oriented design pattern object-oriented cs experience sass/less/postcss framework demonstrated passion user experience design usability familiar experienced making use open source component ability address short term tactical requirement without losing site longer range strategic direction self-motivated discipline meet deadline speed accuracy professional attitude excellent written oral communication skill excellent analytical trouble-shooting skill collaborative team player ability resolve conflict constructive manner work around obstacle ensure project success b computer science equivalent team ’ growing faster pace ever investing heavily cutting-edge technology importantly _our people._ petsmart team ’ department valued business partner every area company every level associate empowered come innovative idea strategic impact business ’ take pride work “ ” behind all—for love pet click meet mike goodwin petsmart ’ cio ’ love home office offer outstanding amenity fun rewarding workplace including pet friendly environment bring pet work ! work-life balance family event movie night art event holiday festival “ top dog ” gym equipment fitness class massage therapist personal trainer “ sit & stay ” café serving fresh breakfast lunch option starbucks cart—productivity finest ! “ lil ’ paw ” learning center onsite childcare facility volunteer event petsmart charity submit resume

In [22]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   address                              784 non-null    object
 1   career_objective                     4740 non-null   object
 2   skills                               9488 non-null   object
 3   educational_institution_name         9460 non-null   object
 4   degree_names                         9460 non-null   object
 5   passing_years                        9460 non-null   object
 6   educational_results                  9460 non-null   object
 7   result_types                         9460 non-null   object
 8   major_field_of_studies               9460 non-null   object
 9   professional_company_names           9460 non-null   object
 10  company_urls                         9460 non-null   object
 11  start_dates                          9460 non-null   object
 12  end_dates                            9460 non-null   object
 13  related_skils_in_job                 9460 non-null   object
 14  positions                            9460 non-null   object
 15  locations                            9460 non-null   object
 16  responsibilities                     9544 non-null   object
 17  extra_curricular_activity_types      3426 non-null   object
 18  extra_curricular_organization_names  3426 non-null   object
 19  extra_curricular_organization_links  3426 non-null   object
 20  role_positions                       3426 non-null   object
 21  languages                            700 non-null    object
 22  proficiency_levels                   700 non-null    object
 23  certification_providers              2008 non-null   object
 24  certification_skills                 2008 non-null   object
 25  online_links                         2008 non-null   object
 26  issue_dates                          2008 non-null   object
 27  expiry_dates                         2008 non-null   object
 28  ﻿job_position_name                   9544 non-null   object
 29  educationaL_requirements             9544 non-null   object
 30  experiencere_requirement             8180 non-null   object
 31  age_requirement                      5457 non-null   object
 32  responsibilities.1                   9544 non-null   object
 33  skills_required                      7843 non-null   object
 34  matched_score                        9544 non-null   float64
dtypes: float64(1), object(34)
memory usage: 2.5+ MB

In [23]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2277 entries, 0 to 2276
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       2277 non-null   int64
 1   Job Title        2277 non-null   object
 2   Job Description  2277 non-null   object
dtypes: int64(1), object(2)
memory usage: 53.5+ KB

In [24]:
resume_df.isnull().sum().sort_values(ascending=False)

languages                              8844
proficiency_levels                     8844
address                                8760
issue_dates                            7536
certification_skills                   7536
certification_providers                7536
expiry_dates                           7536
online_links                           7536
extra_curricular_activity_types        6118
extra_curricular_organization_links    6118
extra_curricular_organization_names    6118
role_positions                         6118
career_objective                       4804
age_requirement                        4087
skills_required                        1701
experiencere_requirement               1364
educational_results                      84
educational_institution_name             84
degree_names                             84
major_field_of_studies                   84
locations                                84
related_skils_in_job                     84
positions                                84
end_dates                                84
start_dates                              84
professional_company_names               84
company_urls                             84
result_types                             84
passing_years                            84
skills                                   56
responsibilities                          0
educationaL_requirements                  0
﻿job_position_name                        0
responsibilities.1                        0
matched_score                             0
dtype: int64

In [25]:
jobs_df.isnull().sum()

Unnamed: 0         0
Job Title          0
Job Description    0
dtype: int64

In [26]:
jobs_df = jobs_df.drop(columns=["Unnamed: 0"])

In [27]:
resume_df["skills"].iloc[0]

"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapreduce', 'Spark', 'Java', 'Machine Learning', 'Cloud', 'Hdfs', 'YARN', 'Core Java', 'Data Science', 'C++', 'Data Structures', 'DBMS', 'RDBMS', 'Informatica', 'Talend', 'Amazon Redshift', 'Microsoft Azure']"

In [28]:
resume_df["responsibilities"].iloc[0]

'Technical Support\nTroubleshooting\nCollaboration\nDocumentation\nSystem Monitoring\nSoftware Deployment\nTraining & Mentorship\nIndustry Trends\nField Visits\n\n\n\n\n'

In [30]:
jobs_df["Job Description"].iloc[0]

'We are looking for hire experts flutter developer. So you are eligible this post then apply your resume.\nJob Types: Full-time, Part-time\nSalary: ₹20,000.00 - ₹40,000.00 per month\nBenefits:\nFlexible schedule\nFood allowance\nSchedule:\nDay shift\nSupplemental Pay:\nJoining bonus\nOvertime pay\nExperience:\ntotal work: 1 year (Preferred)\nHousing rent subsidy:\nYes\nIndustry:\nSoftware Development\nWork Remotely:\nTemporarily due to COVID-19'

In [33]:
print(resume_df.columns.tolist())

['address', 'career_objective', 'skills', 'educational_institution_name', 'degree_names', 'passing_years', 'educational_results', 'result_types', 'major_field_of_studies', 'professional_company_names', 'company_urls', 'start_dates', 'end_dates', 'related_skils_in_job', 'positions', 'locations', 'responsibilities', 'extra_curricular_activity_types', 'extra_curricular_organization_names', 'extra_curricular_organization_links', 'role_positions', 'languages', 'proficiency_levels', 'certification_providers', 'certification_skills', 'online_links', 'issue_dates', 'expiry_dates', '\ufeffjob_position_name', 'educationaL_requirements', 'experiencere_requirement', 'age_requirement', 'responsibilities.1', 'skills_required', 'matched_score']